### PR TITLE
made changes to navbar

### PR DESCRIPTION
**Pull request by sagardesai90**
# Description

Fixes # (issue)

## Type of change
I added a couple items to the bottom navbar. 

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [x] Test A - tested via the expo start command

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by sarahtennis — CHANGES_REQUESTED** [review]
Group vote for npm over yarn

**Review by AquilaVirtual — CHANGES_REQUESTED** [review]
Looks good, but can you use NPM instead of YARN? I think we agreed on that.

**Comment by sagardesai90** [comment]
Ok let me make the changes!

**Review by AquilaVirtual — APPROVED** [review]
Okay, changes look good.

**Review by sarahtennis — APPROVED** [review]

**Pull request merged**
